---
title: "AIM RSF R series: Literate programming with R Markdown"
subtitle: "Based on Data Carpentry: R for Social Scientists"  
author: 
  - "Eirini Zormpa"
date: "13 December 2022 (last updated `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    fig_caption: false
    nature:
      slideNumberFormat: "%current%"
      highlightStyle: github
      highlightLines: true
      ratio: 16:9
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.width=9, fig.height=3.5, fig.retina=3,
  out.width = "100%",
  cache = FALSE,
  echo = TRUE,
  message = FALSE, 
  warning = FALSE,
  hiline = TRUE
)

library(knitr)
library(readr)
library(here)

```

# Summary of session 4: Data visualisation with `ggplot2`

- `r emo::ji("white_check_mark")` Create line plots, scatter plots, and bar plots using `ggplot2`.
- `r emo::ji("white_check_mark")` Apply faceting in `ggplot2`.
- `r emo::ji("white_check_mark")` Build complex and customized plots from data in a data frame.

---
class: center, middle

# Questions?

---

# Learning objectives: Literate programming with `R Markdown`

- `r emo::ji("white_check_mark")` Create a .Rmd document containing R code, text, and plots
- `r emo::ji("white_check_mark")` Create a YAML header to control output
- `r emo::ji("white_check_mark")` Understand basic syntax of (R)Markdown
- `r emo::ji("white_check_mark")` Customise code chunks to control formatting
- `r emo::ji("white_check_mark")` Use code chunks and in-line code to create dynamic, reproducible documents

---

# What is literate programming?

With literate programming, we can combine (nicely formatted!) narrative text with code, all in the same document.

R Markdown is one example of such a document, but you may have also heard of Jupyter notebooks, which do something similar.

I love R Markdown documents because 1. they are reproducible and 2 they are extremely versatile.

---

# Why `R Markdown`: reproducibility `r emo::ji("recycle")`

By combining code and text in the same document:

- it's easier to document your data cleaning and analysis, helping you and other understand your work
- it's easier to avoid copy-paste errors
- it's easier to update your manuscript if you collect more data or change your data cleaning 

---

# Why `R Markdown`: versatility

outputs: reports, slides (like these ones!), journal papers, interactive web apps!

[examples]

---

# Anatomy of an `R Markdown` document

1. YAML header
2. Markdown text
3. Code chunks (supports R, Python, STAN, etc.)

[example]

---
class: center, middle, inverse

# Exercise 1

[Markdown syntax exercise]

---

# `here` for relative paths

---

# The future of `R Markdown`

[Quatro]

---
class: center, middle

# Thank you for your attention and participation throughout this workshop series`r emo::ji("sparkles")` `r emo::ji("pray")`

